hadd TreesMu_TWChannel_plots.root TreesMu_TWChannelFullLep_Q2Down_plots.root TreesMu_TWChannelThadWlep_Q2Down_plots.root TreesMu_TWChannelTlepWhad_Q2Down_plots.root


hadd TreesMu_TbarWChannel_plots.root TreesMu_TbarWChannelFullLep_Q2Down_plots.root TreesMu_TbarWChannelThadWlep_Q2Down_plots.root TreesMu_TbarWChannelTlepWhad_Q2Down_plots.root




