###--------- DD Analysis
./TestMDFit nbin 12 do3D yes channel mu is2Drecgen yes  signal TreesMu_die_TTBar_RW.root signal TreesMu_dimu_TTBar_RW.root signal TreesMu_disemitau_TTBar_RW.root signal TreesMu_ehad_TTBar_RW.root signal TreesMu_etau_TTBar_RW.root signal TreesMu_mue_TTBar_RW.root signal TreesMu_muhad_TTBar_RW.root signal TreesMu_mutau_TTBar_RW.root signal TreesMu_SbarChannel_RW.root signal TreesMu_SChannel_RW.root signal TreesMu_TbarChannel_RW.root signal TreesMu_TbarWChannel_RW.root signal TreesMu_TChannel_RW.root signal TreesMu_TWChannel_RW.root bkg TreesMu_bkg_RW.root wtemplate TreesMu_WTemplateDefFormat_RW.root data TreesMu_Data_plots.root > ../DD/nBin360/mujet_30bin.txt

./TestMDFit nbin 9 do3D yes channel mu is2Drecgen yes  signal TreesMu_die_TTBar_RW.root signal TreesMu_dimu_TTBar_RW.root signal TreesMu_disemitau_TTBar_RW.root signal TreesMu_ehad_TTBar_RW.root signal TreesMu_etau_TTBar_RW.root signal TreesMu_mue_TTBar_RW.root signal TreesMu_muhad_TTBar_RW.root signal TreesMu_mutau_TTBar_RW.root signal TreesMu_SbarChannel_RW.root signal TreesMu_SChannel_RW.root signal TreesMu_TbarChannel_RW.root signal TreesMu_TbarWChannel_RW.root signal TreesMu_TChannel_RW.root signal TreesMu_TWChannel_RW.root bkg TreesMu_bkg_RW.root wtemplate TreesMu_WTemplateDefFormat_RW.root data TreesMu_Data_plots.root > ../DD/nBin360/mujet_40bin.txt

./TestMDFit nbin 6 do3D yes channel mu is2Drecgen yes  signal TreesMu_die_TTBar_RW.root signal TreesMu_dimu_TTBar_RW.root signal TreesMu_disemitau_TTBar_RW.root signal TreesMu_ehad_TTBar_RW.root signal TreesMu_etau_TTBar_RW.root signal TreesMu_mue_TTBar_RW.root signal TreesMu_muhad_TTBar_RW.root signal TreesMu_mutau_TTBar_RW.root signal TreesMu_SbarChannel_RW.root signal TreesMu_SChannel_RW.root signal TreesMu_TbarChannel_RW.root signal TreesMu_TbarWChannel_RW.root signal TreesMu_TChannel_RW.root signal TreesMu_TWChannel_RW.root bkg TreesMu_bkg_RW.root wtemplate TreesMu_WTemplateDefFormat_RW.root data TreesMu_Data_plots.root > ../DD/nBin360/mujet_60bin.txt

./TestMDFit nbin 5  do3D yes channel mu is2Drecgen yes  signal TreesMu_die_TTBar_RW.root signal TreesMu_dimu_TTBar_RW.root signal TreesMu_disemitau_TTBar_RW.root signal TreesMu_ehad_TTBar_RW.root signal TreesMu_etau_TTBar_RW.root signal TreesMu_mue_TTBar_RW.root signal TreesMu_muhad_TTBar_RW.root signal TreesMu_mutau_TTBar_RW.root signal TreesMu_SbarChannel_RW.root signal TreesMu_SChannel_RW.root signal TreesMu_TbarChannel_RW.root signal TreesMu_TbarWChannel_RW.root signal TreesMu_TChannel_RW.root signal TreesMu_TWChannel_RW.root bkg TreesMu_bkg_RW.root wtemplate TreesMu_WTemplateDefFormat_RW.root data TreesMu_Data_plots.root > ../DD/nBin360/mujet_72bin.txt

./TestMDFit nbin 4 do3D yes channel mu is2Drecgen yes  signal TreesMu_die_TTBar_RW.root signal TreesMu_dimu_TTBar_RW.root signal TreesMu_disemitau_TTBar_RW.root signal TreesMu_ehad_TTBar_RW.root signal TreesMu_etau_TTBar_RW.root signal TreesMu_mue_TTBar_RW.root signal TreesMu_muhad_TTBar_RW.root signal TreesMu_mutau_TTBar_RW.root signal TreesMu_SbarChannel_RW.root signal TreesMu_SChannel_RW.root signal TreesMu_TbarChannel_RW.root signal TreesMu_TbarWChannel_RW.root signal TreesMu_TChannel_RW.root signal TreesMu_TWChannel_RW.root bkg TreesMu_bkg_RW.root wtemplate TreesMu_WTemplateDefFormat_RW.root data TreesMu_Data_plots.root > ../DD/nBin360/mujet_90bin.txt


