#./TestMDFit do3D yes channel e is2Drecgen yes  signal TreesEle_die_TTBar_RW.root signal TreesEle_dimu_TTBar_RW.root signal TreesEle_disemitau_TTBar_RW.root signal TreesEle_ehad_TTBar_RW.root signal TreesEle_etau_TTBar_RW.root signal TreesEle_mue_TTBar_RW.root signal TreesEle_muhad_TTBar_RW.root signal TreesEle_mutau_TTBar_RW.root signal TreesEle_SbarChannel_RW.root signal TreesEle_SChannel_RW.root signal TreesEle_TbarChannel_RW.root signal TreesEle_TbarWChannel_RW.root signal TreesEle_TChannel_RW.root signal TreesEle_TWChannel_RW.root bkg TreesEle_bkg_RW.root wtemplate TreesEle_WTemplateDefFormat_plots.root data TreesEle_Data_plots.root > WData_RWTT_fixW.txt


#./TestMDFit do3D yes channel e is2Drecgen yes  signal TreesEle_die_TTBar_RW.root signal TreesEle_dimu_TTBar_RW.root signal TreesEle_disemitau_TTBar_RW.root signal TreesEle_ehad_TTBar_RW.root signal TreesEle_etau_TTBar_RW.root signal TreesEle_mue_TTBar_RW.root signal TreesEle_muhad_TTBar_RW.root signal TreesEle_mutau_TTBar_RW.root signal TreesEle_SbarChannel_RW.root signal TreesEle_SChannel_RW.root signal TreesEle_TbarChannel_RW.root signal TreesEle_TbarWChannel_RW.root signal TreesEle_TChannel_RW.root signal TreesEle_TWChannel_RW.root bkg TreesEle_bkg_RW.root wtemplate TreesEle_WJets_RW.root data TreesEle_Data_plots.root > WMC_RWTT_fixW.txt


#./TestMDFit do3D yes channel e is2Drecgen yes  signal TreesEle_die_TTBar_RW.root signal TreesEle_dimu_TTBar_RW.root signal TreesEle_disemitau_TTBar_RW.root signal TreesEle_ehad_TTBar_RW.root signal TreesEle_etau_TTBar_RW.root signal TreesEle_mue_TTBar_RW.root signal TreesEle_muhad_TTBar_RW.root signal TreesEle_mutau_TTBar_RW.root signal TreesEle_SbarChannel_RW.root signal TreesEle_SChannel_RW.root signal TreesEle_TbarChannel_RW.root signal TreesEle_TbarWChannel_RW.root signal TreesEle_TChannel_RW.root signal TreesEle_TWChannel_RW.root bkg mubkg.root wtemplate TreesEle_WTemplateDefFormat_plots.root data TreesEle_Data_plots.root > WData_MuQCD.txt

#./TestMDFit do3D yes channel e is2Drecgen yes  signal TreesEle_die_TTBar_RW.root signal TreesEle_dimu_TTBar_RW.root signal TreesEle_disemitau_TTBar_RW.root signal TreesEle_ehad_TTBar_RW.root signal TreesEle_etau_TTBar_RW.root signal TreesEle_mue_TTBar_RW.root signal TreesEle_muhad_TTBar_RW.root signal TreesEle_mutau_TTBar_RW.root signal TreesEle_SbarChannel_RW.root signal TreesEle_SChannel_RW.root signal TreesEle_TbarChannel_RW.root signal TreesEle_TbarWChannel_RW.root signal TreesEle_TChannel_RW.root signal TreesEle_TWChannel_RW.root bkg mubkg.root wtemplate TreesEle_WJets_RW.root data TreesEle_Data_plots.root > WMC_MuQCD.txt

###--------- MGSHRW Analysis

#./TestMDFitEMTWWfixed do3D yes channel e is2Drecgen yes  signal TreesEle_die_TTBar_RW.root signal TreesEle_dimu_TTBar_RW.root signal TreesEle_disemitau_TTBar_RW.root signal TreesEle_ehad_TTBar_RW.root signal TreesEle_etau_TTBar_RW.root signal TreesEle_mue_TTBar_RW.root signal TreesEle_muhad_TTBar_RW.root signal TreesEle_mutau_TTBar_RW.root signal TreesEle_SbarChannel_RW.root signal TreesEle_SChannel_RW.root signal TreesEle_TbarChannel_RW.root signal TreesEle_TbarWChannel_RW.root signal TreesEle_TChannel_RW.root signal TreesEle_TWChannel_RW.root bkg TreesEle_bkg_RW.root wtemplate TreesEle_WJetsMGSHRW_RW.root data TreesEle_Data_plots.root > MGSHRW/ejet_fixW_10bin.txt

#./TestMDFit do3D yes channel e is2Drecgen yes  signal TreesEle_die_TTBar_RW.root signal TreesEle_dimu_TTBar_RW.root signal TreesEle_disemitau_TTBar_RW.root signal TreesEle_ehad_TTBar_RW.root signal TreesEle_etau_TTBar_RW.root signal TreesEle_mue_TTBar_RW.root signal TreesEle_muhad_TTBar_RW.root signal TreesEle_mutau_TTBar_RW.root signal TreesEle_SbarChannel_RW.root signal TreesEle_SChannel_RW.root signal TreesEle_TbarChannel_RW.root signal TreesEle_TbarWChannel_RW.root signal TreesEle_TChannel_RW.root signal TreesEle_TWChannel_RW.root bkg TreesEle_bkg_RW.root wtemplate TreesEle_WJetsMGSHRW_RW.root data TreesEle_Data_plots.root > MGSHRW/ejet_10bin.txt

#./TestMDFit100 do3D yes channel e is2Drecgen yes  signal TreesEle_die_TTBar_RW.root signal TreesEle_dimu_TTBar_RW.root signal TreesEle_disemitau_TTBar_RW.root signal TreesEle_ehad_TTBar_RW.root signal TreesEle_etau_TTBar_RW.root signal TreesEle_mue_TTBar_RW.root signal TreesEle_muhad_TTBar_RW.root signal TreesEle_mutau_TTBar_RW.root signal TreesEle_SbarChannel_RW.root signal TreesEle_SChannel_RW.root signal TreesEle_TbarChannel_RW.root signal TreesEle_TbarWChannel_RW.root signal TreesEle_TChannel_RW.root signal TreesEle_TWChannel_RW.root bkg TreesEle_bkg_RW.root wtemplate TreesEle_WJetsMGSHRW_RW.root data TreesEle_Data_plots.root > MGSHRW/ejet_100bin.txt

###--------- MG Analysis

./TestMDFitEMTWWfixed do3D yes channel e is2Drecgen yes  signal TreesEle_die_TTBar_RW.root signal TreesEle_dimu_TTBar_RW.root signal TreesEle_disemitau_TTBar_RW.root signal TreesEle_ehad_TTBar_RW.root signal TreesEle_etau_TTBar_RW.root signal TreesEle_mue_TTBar_RW.root signal TreesEle_muhad_TTBar_RW.root signal TreesEle_mutau_TTBar_RW.root signal TreesEle_SbarChannel_RW.root signal TreesEle_SChannel_RW.root signal TreesEle_TbarChannel_RW.root signal TreesEle_TbarWChannel_RW.root signal TreesEle_TChannel_RW.root signal TreesEle_TWChannel_RW.root bkg TreesEle_bkg_RW.root wtemplate TreesEle_WJets_RW.root data TreesEle_Data_plots.root > MG/ejet_fixW_10bin.txt

./TestMDFit do3D yes channel e is2Drecgen yes  signal TreesEle_die_TTBar_RW.root signal TreesEle_dimu_TTBar_RW.root signal TreesEle_disemitau_TTBar_RW.root signal TreesEle_ehad_TTBar_RW.root signal TreesEle_etau_TTBar_RW.root signal TreesEle_mue_TTBar_RW.root signal TreesEle_muhad_TTBar_RW.root signal TreesEle_mutau_TTBar_RW.root signal TreesEle_SbarChannel_RW.root signal TreesEle_SChannel_RW.root signal TreesEle_TbarChannel_RW.root signal TreesEle_TbarWChannel_RW.root signal TreesEle_TChannel_RW.root signal TreesEle_TWChannel_RW.root bkg TreesEle_bkg_RW.root wtemplate TreesEle_WJets_RW.root data TreesEle_Data_plots.root > MG/ejet_10bin.txt

./TestMDFit100 do3D yes channel e is2Drecgen yes  signal TreesEle_die_TTBar_RW.root signal TreesEle_dimu_TTBar_RW.root signal TreesEle_disemitau_TTBar_RW.root signal TreesEle_ehad_TTBar_RW.root signal TreesEle_etau_TTBar_RW.root signal TreesEle_mue_TTBar_RW.root signal TreesEle_muhad_TTBar_RW.root signal TreesEle_mutau_TTBar_RW.root signal TreesEle_SbarChannel_RW.root signal TreesEle_SChannel_RW.root signal TreesEle_TbarChannel_RW.root signal TreesEle_TbarWChannel_RW.root signal TreesEle_TChannel_RW.root signal TreesEle_TWChannel_RW.root bkg TreesEle_bkg_RW.root wtemplate TreesEle_WJets_RW.root data TreesEle_Data_plots.root > MG/ejet_100bin.txt

###--------- DD Analysis

./TestMDFitEMTWWfixed do3D yes channel e is2Drecgen yes  signal TreesEle_die_TTBar_RW.root signal TreesEle_dimu_TTBar_RW.root signal TreesEle_disemitau_TTBar_RW.root signal TreesEle_ehad_TTBar_RW.root signal TreesEle_etau_TTBar_RW.root signal TreesEle_mue_TTBar_RW.root signal TreesEle_muhad_TTBar_RW.root signal TreesEle_mutau_TTBar_RW.root signal TreesEle_SbarChannel_RW.root signal TreesEle_SChannel_RW.root signal TreesEle_TbarChannel_RW.root signal TreesEle_TbarWChannel_RW.root signal TreesEle_TChannel_RW.root signal TreesEle_TWChannel_RW.root bkg TreesEle_bkg_RW.root wtemplate QCDFreeWJets.root data TreesEle_Data_plots.root > DD/ejet_fixW_10bin.txt

./TestMDFit do3D yes channel e is2Drecgen yes  signal TreesEle_die_TTBar_RW.root signal TreesEle_dimu_TTBar_RW.root signal TreesEle_disemitau_TTBar_RW.root signal TreesEle_ehad_TTBar_RW.root signal TreesEle_etau_TTBar_RW.root signal TreesEle_mue_TTBar_RW.root signal TreesEle_muhad_TTBar_RW.root signal TreesEle_mutau_TTBar_RW.root signal TreesEle_SbarChannel_RW.root signal TreesEle_SChannel_RW.root signal TreesEle_TbarChannel_RW.root signal TreesEle_TbarWChannel_RW.root signal TreesEle_TChannel_RW.root signal TreesEle_TWChannel_RW.root bkg TreesEle_bkg_RW.root wtemplate QCDFreeWJets.root data TreesEle_Data_plots.root > DD/ejet_10bin.txt

./TestMDFit100 do3D yes channel e is2Drecgen yes  signal TreesEle_die_TTBar_RW.root signal TreesEle_dimu_TTBar_RW.root signal TreesEle_disemitau_TTBar_RW.root signal TreesEle_ehad_TTBar_RW.root signal TreesEle_etau_TTBar_RW.root signal TreesEle_mue_TTBar_RW.root signal TreesEle_muhad_TTBar_RW.root signal TreesEle_mutau_TTBar_RW.root signal TreesEle_SbarChannel_RW.root signal TreesEle_SChannel_RW.root signal TreesEle_TbarChannel_RW.root signal TreesEle_TbarWChannel_RW.root signal TreesEle_TChannel_RW.root signal TreesEle_TWChannel_RW.root bkg TreesEle_bkg_RW.root wtemplate QCDFreeWJets.root data TreesEle_Data_plots.root > DD/ejet_100bin.txt
