###--------- MGSHRW Analysis

#./TestMDFitTrueEMETWfixed do3D yes channel e is2Drecgen yes  signal TreesEle_die_TTBar_RW.root signal TreesEle_dimu_TTBar_RW.root signal TreesEle_disemitau_TTBar_RW.root signal TreesEle_ehad_TTBar_RW.root signal TreesEle_etau_TTBar_RW.root signal TreesEle_mue_TTBar_RW.root signal TreesEle_muhad_TTBar_RW.root signal TreesEle_mutau_TTBar_RW.root signal TreesEle_SbarChannel_RW.root signal TreesEle_SChannel_RW.root signal TreesEle_TbarChannel_RW.root signal TreesEle_TbarWChannel_RW.root signal TreesEle_TChannel_RW.root signal TreesEle_TWChannel_RW.root bkg TreesEle_bkgEle_RW.root wtemplate TreesEle_WJetsMGSHRW_RW.root data TreesEle_Data_plots.root > MGSHRW/ejet_fixW_10bin.txt

#./TestMDFitTrue do3D yes channel e is2Drecgen yes  signal TreesEle_die_TTBar_RW.root signal TreesEle_dimu_TTBar_RW.root signal TreesEle_disemitau_TTBar_RW.root signal TreesEle_ehad_TTBar_RW.root signal TreesEle_etau_TTBar_RW.root signal TreesEle_mue_TTBar_RW.root signal TreesEle_muhad_TTBar_RW.root signal TreesEle_mutau_TTBar_RW.root signal TreesEle_SbarChannel_RW.root signal TreesEle_SChannel_RW.root signal TreesEle_TbarChannel_RW.root signal TreesEle_TbarWChannel_RW.root signal TreesEle_TChannel_RW.root signal TreesEle_TWChannel_RW.root bkg TreesEle_bkgEle_RW.root wtemplate TreesEle_WJetsMGSHRW_RW.root data TreesEle_Data_plots.root > MGSHRW/ejet_10bin.txt

#./TestMDFitTrue100 do3D yes channel e is2Drecgen yes  signal TreesEle_die_TTBar_RW.root signal TreesEle_dimu_TTBar_RW.root signal TreesEle_disemitau_TTBar_RW.root signal TreesEle_ehad_TTBar_RW.root signal TreesEle_etau_TTBar_RW.root signal TreesEle_mue_TTBar_RW.root signal TreesEle_muhad_TTBar_RW.root signal TreesEle_mutau_TTBar_RW.root signal TreesEle_SbarChannel_RW.root signal TreesEle_SChannel_RW.root signal TreesEle_TbarChannel_RW.root signal TreesEle_TbarWChannel_RW.root signal TreesEle_TChannel_RW.root signal TreesEle_TWChannel_RW.root bkg TreesEle_bkgEle_RW.root wtemplate TreesEle_WJetsMGSHRW_RW.root data TreesEle_Data_plots.root > MGSHRW/ejet_100bin.txt

###--------- MG Analysis

#./TestMDFitTrueEMETWfixed do3D yes channel e is2Drecgen yes  signal TreesEle_die_TTBar_RW.root signal TreesEle_dimu_TTBar_RW.root signal TreesEle_disemitau_TTBar_RW.root signal TreesEle_ehad_TTBar_RW.root signal TreesEle_etau_TTBar_RW.root signal TreesEle_mue_TTBar_RW.root signal TreesEle_muhad_TTBar_RW.root signal TreesEle_mutau_TTBar_RW.root signal TreesEle_SbarChannel_RW.root signal TreesEle_SChannel_RW.root signal TreesEle_TbarChannel_RW.root signal TreesEle_TbarWChannel_RW.root signal TreesEle_TChannel_RW.root signal TreesEle_TWChannel_RW.root bkg TreesEle_bkgEle_RW.root wtemplate TreesEle_WJets_RW.root data TreesEle_Data_plots.root > MG/ejet_fixW_10bin.txt

./FixedFrTestMDFit directory DefaultTrue_allW nbin 1 do3D yes channel e is2Drecgen yes  signal TreesEle_die_TTBar_RW.root signal TreesEle_dimu_TTBar_RW.root signal TreesEle_disemitau_TTBar_RW.root signal TreesEle_ehad_TTBar_RW.root signal TreesEle_etau_TTBar_RW.root signal TreesEle_mue_TTBar_RW.root signal TreesEle_muhad_TTBar_RW.root signal TreesEle_mutau_TTBar_RW.root signal TreesEle_SbarChannel_RW.root signal TreesEle_SChannel_RW.root signal TreesEle_TbarChannel_RW.root signal TreesEle_TbarWChannel_RW.root signal TreesEle_TChannel_RW.root signal TreesEle_TWChannel_RW.root bkg TreesEle_bkgEle_RW.root wtemplate TreesEle_WJets_RW.root data TreesEle_Data_plots.root > MG/ejet_fixFr_100bin.txt

./FixedFzTestMDFit directory DefaultTrue_allW nbin 1 do3D yes channel e is2Drecgen yes  signal TreesEle_die_TTBar_RW.root signal TreesEle_dimu_TTBar_RW.root signal TreesEle_disemitau_TTBar_RW.root signal TreesEle_ehad_TTBar_RW.root signal TreesEle_etau_TTBar_RW.root signal TreesEle_mue_TTBar_RW.root signal TreesEle_muhad_TTBar_RW.root signal TreesEle_mutau_TTBar_RW.root signal TreesEle_SbarChannel_RW.root signal TreesEle_SChannel_RW.root signal TreesEle_TbarChannel_RW.root signal TreesEle_TbarWChannel_RW.root signal TreesEle_TChannel_RW.root signal TreesEle_TWChannel_RW.root bkg TreesEle_bkgEle_RW.root wtemplate TreesEle_WJets_RW.root data TreesEle_Data_plots.root > MG/ejet_fixF0_100bin.txt

./FixedFlTestMDFit directory DefaultTrue_allW nbin 1 do3D yes channel e is2Drecgen yes  signal TreesEle_die_TTBar_RW.root signal TreesEle_dimu_TTBar_RW.root signal TreesEle_disemitau_TTBar_RW.root signal TreesEle_ehad_TTBar_RW.root signal TreesEle_etau_TTBar_RW.root signal TreesEle_mue_TTBar_RW.root signal TreesEle_muhad_TTBar_RW.root signal TreesEle_mutau_TTBar_RW.root signal TreesEle_SbarChannel_RW.root signal TreesEle_SChannel_RW.root signal TreesEle_TbarChannel_RW.root signal TreesEle_TbarWChannel_RW.root signal TreesEle_TChannel_RW.root signal TreesEle_TWChannel_RW.root bkg TreesEle_bkgEle_RW.root wtemplate TreesEle_WJets_RW.root data TreesEle_Data_plots.root > MG/ejet_fixFl_100bin.txt

###--------- DD Analysis

#./TestMDFitTrueEMETWfixed do3D yes channel e is2Drecgen yes  signal TreesEle_die_TTBar_RW.root signal TreesEle_dimu_TTBar_RW.root signal TreesEle_disemitau_TTBar_RW.root signal TreesEle_ehad_TTBar_RW.root signal TreesEle_etau_TTBar_RW.root signal TreesEle_mue_TTBar_RW.root signal TreesEle_muhad_TTBar_RW.root signal TreesEle_mutau_TTBar_RW.root signal TreesEle_SbarChannel_RW.root signal TreesEle_SChannel_RW.root signal TreesEle_TbarChannel_RW.root signal TreesEle_TbarWChannel_RW.root signal TreesEle_TChannel_RW.root signal TreesEle_TWChannel_RW.root bkg TreesEle_bkgEle_RW.root wtemplate TreesEle_WTemplateDefFormat_RW.root data TreesEle_Data_plots.root > DD/ejet_fixW_10bin.txt

./FixedFrTestMDFit directory DefaultTrue_allW nbin 1 do3D yes channel e is2Drecgen yes  signal TreesEle_die_TTBar_RW.root signal TreesEle_dimu_TTBar_RW.root signal TreesEle_disemitau_TTBar_RW.root signal TreesEle_ehad_TTBar_RW.root signal TreesEle_etau_TTBar_RW.root signal TreesEle_mue_TTBar_RW.root signal TreesEle_muhad_TTBar_RW.root signal TreesEle_mutau_TTBar_RW.root signal TreesEle_SbarChannel_RW.root signal TreesEle_SChannel_RW.root signal TreesEle_TbarChannel_RW.root signal TreesEle_TbarWChannel_RW.root signal TreesEle_TChannel_RW.root signal TreesEle_TWChannel_RW.root bkg TreesEle_bkgEle_RW.root wtemplate TreesEle_WTemplateDefFormat_RW.root data TreesEle_Data_plots.root > DD/ejet_fixFr_100bin.txt

./FixedFzTestMDFit directory DefaultTrue_allW nbin 1 do3D yes channel e is2Drecgen yes  signal TreesEle_die_TTBar_RW.root signal TreesEle_dimu_TTBar_RW.root signal TreesEle_disemitau_TTBar_RW.root signal TreesEle_ehad_TTBar_RW.root signal TreesEle_etau_TTBar_RW.root signal TreesEle_mue_TTBar_RW.root signal TreesEle_muhad_TTBar_RW.root signal TreesEle_mutau_TTBar_RW.root signal TreesEle_SbarChannel_RW.root signal TreesEle_SChannel_RW.root signal TreesEle_TbarChannel_RW.root signal TreesEle_TbarWChannel_RW.root signal TreesEle_TChannel_RW.root signal TreesEle_TWChannel_RW.root bkg TreesEle_bkgEle_RW.root wtemplate TreesEle_WTemplateDefFormat_RW.root data TreesEle_Data_plots.root > DD/ejet_fixF0_100bin.txt

./FixedFlTestMDFit directory DefaultTrue_allW nbin 1 do3D yes channel e is2Drecgen yes  signal TreesEle_die_TTBar_RW.root signal TreesEle_dimu_TTBar_RW.root signal TreesEle_disemitau_TTBar_RW.root signal TreesEle_ehad_TTBar_RW.root signal TreesEle_etau_TTBar_RW.root signal TreesEle_mue_TTBar_RW.root signal TreesEle_muhad_TTBar_RW.root signal TreesEle_mutau_TTBar_RW.root signal TreesEle_SbarChannel_RW.root signal TreesEle_SChannel_RW.root signal TreesEle_TbarChannel_RW.root signal TreesEle_TbarWChannel_RW.root signal TreesEle_TChannel_RW.root signal TreesEle_TWChannel_RW.root bkg TreesEle_bkgEle_RW.root wtemplate TreesEle_WTemplateDefFormat_RW.root data TreesEle_Data_plots.root > DD/ejet_fixFl_100bin.txt
