#./TestMDFit do3D yes channel mu is2Drecgen yes  signal TreesMu_die_TTBar_RW.root signal TreesMu_dimu_TTBar_RW.root signal TreesMu_disemitau_TTBar_RW.root signal TreesMu_ehad_TTBar_RW.root signal TreesMu_etau_TTBar_RW.root signal TreesMu_mue_TTBar_RW.root signal TreesMu_muhad_TTBar_RW.root signal TreesMu_mutau_TTBar_RW.root signal TreesMu_SbarChannel_RW.root signal TreesMu_SChannel_RW.root signal TreesMu_TbarChannel_RW.root signal TreesMu_TbarWChannel_RW.root signal TreesMu_TChannel_RW.root signal TreesMu_TWChannel_RW.root bkg TreesMu_bkg_RW.root wtemplate TreesMu_WTemplateDefFormat_plots.root data TreesMu_Data_plots.root > mujet_fixW.txt



###--------- MGSHRW Analysis

#./TestMDFitMuWfixed do3D yes channel mu is2Drecgen yes  signal TreesMu_die_TTBar_RW.root signal TreesMu_dimu_TTBar_RW.root signal TreesMu_disemitau_TTBar_RW.root signal TreesMu_ehad_TTBar_RW.root signal TreesMu_etau_TTBar_RW.root signal TreesMu_mue_TTBar_RW.root signal TreesMu_muhad_TTBar_RW.root signal TreesMu_mutau_TTBar_RW.root signal TreesMu_SbarChannel_RW.root signal TreesMu_SChannel_RW.root signal TreesMu_TbarChannel_RW.root signal TreesMu_TbarWChannel_RW.root signal TreesMu_TChannel_RW.root signal TreesMu_TWChannel_RW.root bkg TreesMu_bkg_RW.root wtemplate TreesMu_WJetsMGSHRW_RW.root data TreesMu_Data_plots.root > MGSHRW/mujet_fixW_10bin.txt

#./TestMDFit do3D yes channel mu is2Drecgen yes  signal TreesMu_die_TTBar_RW.root signal TreesMu_dimu_TTBar_RW.root signal TreesMu_disemitau_TTBar_RW.root signal TreesMu_ehad_TTBar_RW.root signal TreesMu_etau_TTBar_RW.root signal TreesMu_mue_TTBar_RW.root signal TreesMu_muhad_TTBar_RW.root signal TreesMu_mutau_TTBar_RW.root signal TreesMu_SbarChannel_RW.root signal TreesMu_SChannel_RW.root signal TreesMu_TbarChannel_RW.root signal TreesMu_TbarWChannel_RW.root signal TreesMu_TChannel_RW.root signal TreesMu_TWChannel_RW.root bkg TreesMu_bkg_RW.root wtemplate TreesMu_WJetsMGSHRW_RW.root data TreesMu_Data_plots.root > MGSHRW/mujet_10bin.txt

#./TestMDFit100 do3D yes channel mu is2Drecgen yes  signal TreesMu_die_TTBar_RW.root signal TreesMu_dimu_TTBar_RW.root signal TreesMu_disemitau_TTBar_RW.root signal TreesMu_ehad_TTBar_RW.root signal TreesMu_etau_TTBar_RW.root signal TreesMu_mue_TTBar_RW.root signal TreesMu_muhad_TTBar_RW.root signal TreesMu_mutau_TTBar_RW.root signal TreesMu_SbarChannel_RW.root signal TreesMu_SChannel_RW.root signal TreesMu_TbarChannel_RW.root signal TreesMu_TbarWChannel_RW.root signal TreesMu_TChannel_RW.root signal TreesMu_TWChannel_RW.root bkg TreesMu_bkg_RW.root wtemplate TreesMu_WJetsMGSHRW_RW.root data TreesMu_Data_plots.root > MGSHRW/mujet_100bin.txt

###--------- MG Analysis

#./TestMDFitMuWfixed do3D yes channel mu is2Drecgen yes  signal TreesMu_die_TTBar_RW.root signal TreesMu_dimu_TTBar_RW.root signal TreesMu_disemitau_TTBar_RW.root signal TreesMu_ehad_TTBar_RW.root signal TreesMu_etau_TTBar_RW.root signal TreesMu_mue_TTBar_RW.root signal TreesMu_muhad_TTBar_RW.root signal TreesMu_mutau_TTBar_RW.root signal TreesMu_SbarChannel_RW.root signal TreesMu_SChannel_RW.root signal TreesMu_TbarChannel_RW.root signal TreesMu_TbarWChannel_RW.root signal TreesMu_TChannel_RW.root signal TreesMu_TWChannel_RW.root bkg TreesMu_bkg_RW.root wtemplate TreesMu_WJets_RW.root data TreesMu_Data_plots.root > MG/mujet_fixW_10bin.txt

#./TestMDFit do3D yes channel mu is2Drecgen yes  signal TreesMu_die_TTBar_RW.root signal TreesMu_dimu_TTBar_RW.root signal TreesMu_disemitau_TTBar_RW.root signal TreesMu_ehad_TTBar_RW.root signal TreesMu_etau_TTBar_RW.root signal TreesMu_mue_TTBar_RW.root signal TreesMu_muhad_TTBar_RW.root signal TreesMu_mutau_TTBar_RW.root signal TreesMu_SbarChannel_RW.root signal TreesMu_SChannel_RW.root signal TreesMu_TbarChannel_RW.root signal TreesMu_TbarWChannel_RW.root signal TreesMu_TChannel_RW.root signal TreesMu_TWChannel_RW.root bkg TreesMu_bkg_RW.root wtemplate TreesMu_WJets_RW.root data TreesMu_Data_plots.root > MG/mujet_10bin.txt

#./TestMDFit100 do3D yes channel mu is2Drecgen yes  signal TreesMu_die_TTBar_RW.root signal TreesMu_dimu_TTBar_RW.root signal TreesMu_disemitau_TTBar_RW.root signal TreesMu_ehad_TTBar_RW.root signal TreesMu_etau_TTBar_RW.root signal TreesMu_mue_TTBar_RW.root signal TreesMu_muhad_TTBar_RW.root signal TreesMu_mutau_TTBar_RW.root signal TreesMu_SbarChannel_RW.root signal TreesMu_SChannel_RW.root signal TreesMu_TbarChannel_RW.root signal TreesMu_TbarWChannel_RW.root signal TreesMu_TChannel_RW.root signal TreesMu_TWChannel_RW.root bkg TreesMu_bkg_RW.root wtemplate TreesMu_WJets_RW.root data TreesMu_Data_plots.root > MG/mujet_100bin.txt
####--------- Dphi
./TestMDFit do3D yes channel mu is2Drecgen yes  signal TreesMu_die_TTBar_RW.root signal TreesMu_dimu_TTBar_RW.root signal TreesMu_disemitau_TTBar_RW.root signal TreesMu_ehad_TTBar_RW.root signal TreesMu_etau_TTBar_RW.root signal TreesMu_mue_TTBar_RW.root signal TreesMu_muhad_TTBar_RW.root signal TreesMu_mutau_TTBar_RW.root signal TreesMu_SbarChannel_RW.root signal TreesMu_SChannel_RW.root signal TreesMu_TbarChannel_RW.root signal TreesMu_TbarWChannel_RW.root signal TreesMu_TChannel_RW.root signal TreesMu_TWChannel_RW.root bkg TreesMu_bkgPhi_RW.root wtemplate TreesMu_WJets_RW.root data TreesMu_Data_plots.root > MG/mujet_10bin_phi.txt

./TestMDFit100 do3D yes channel mu is2Drecgen yes  signal TreesMu_die_TTBar_RW.root signal TreesMu_dimu_TTBar_RW.root signal TreesMu_disemitau_TTBar_RW.root signal TreesMu_ehad_TTBar_RW.root signal TreesMu_etau_TTBar_RW.root signal TreesMu_mue_TTBar_RW.root signal TreesMu_muhad_TTBar_RW.root signal TreesMu_mutau_TTBar_RW.root signal TreesMu_SbarChannel_RW.root signal TreesMu_SChannel_RW.root signal TreesMu_TbarChannel_RW.root signal TreesMu_TbarWChannel_RW.root signal TreesMu_TChannel_RW.root signal TreesMu_TWChannel_RW.root bkg TreesMu_bkgPhi_RW.root wtemplate TreesMu_WJets_RW.root data TreesMu_Data_plots.root > MG/mujet_100bin_phi.txt

####--------- Dr
./TestMDFit do3D yes channel mu is2Drecgen yes  signal TreesMu_die_TTBar_RW.root signal TreesMu_dimu_TTBar_RW.root signal TreesMu_disemitau_TTBar_RW.root signal TreesMu_ehad_TTBar_RW.root signal TreesMu_etau_TTBar_RW.root signal TreesMu_mue_TTBar_RW.root signal TreesMu_muhad_TTBar_RW.root signal TreesMu_mutau_TTBar_RW.root signal TreesMu_SbarChannel_RW.root signal TreesMu_SChannel_RW.root signal TreesMu_TbarChannel_RW.root signal TreesMu_TbarWChannel_RW.root signal TreesMu_TChannel_RW.root signal TreesMu_TWChannel_RW.root bkg TreesMu_bkgdr_RW.root wtemplate TreesMu_WJets_RW.root data TreesMu_Data_plots.root > MG/mujet_10bin_dr.txt

./TestMDFit100 do3D yes channel mu is2Drecgen yes  signal TreesMu_die_TTBar_RW.root signal TreesMu_dimu_TTBar_RW.root signal TreesMu_disemitau_TTBar_RW.root signal TreesMu_ehad_TTBar_RW.root signal TreesMu_etau_TTBar_RW.root signal TreesMu_mue_TTBar_RW.root signal TreesMu_muhad_TTBar_RW.root signal TreesMu_mutau_TTBar_RW.root signal TreesMu_SbarChannel_RW.root signal TreesMu_SChannel_RW.root signal TreesMu_TbarChannel_RW.root signal TreesMu_TbarWChannel_RW.root signal TreesMu_TChannel_RW.root signal TreesMu_TWChannel_RW.root bkg TreesMu_bkgdr_RW.root wtemplate TreesMu_WJets_RW.root data TreesMu_Data_plots.root > MG/mujet_100bin_dr.txt


###--------- DD Analysis

#./TestMDFitMuWfixed do3D yes channel mu is2Drecgen yes  signal TreesMu_die_TTBar_RW.root signal TreesMu_dimu_TTBar_RW.root signal TreesMu_disemitau_TTBar_RW.root signal TreesMu_ehad_TTBar_RW.root signal TreesMu_etau_TTBar_RW.root signal TreesMu_mue_TTBar_RW.root signal TreesMu_muhad_TTBar_RW.root signal TreesMu_mutau_TTBar_RW.root signal TreesMu_SbarChannel_RW.root signal TreesMu_SChannel_RW.root signal TreesMu_TbarChannel_RW.root signal TreesMu_TbarWChannel_RW.root signal TreesMu_TChannel_RW.root signal TreesMu_TWChannel_RW.root bkg TreesMu_bkg_RW.root wtemplate TreesMu_WTemplateDefFormat_RW.root data TreesMu_Data_plots.root > DD/mujet_fixW_10bin.txt

#./TestMDFit do3D yes channel mu is2Drecgen yes  signal TreesMu_die_TTBar_RW.root signal TreesMu_dimu_TTBar_RW.root signal TreesMu_disemitau_TTBar_RW.root signal TreesMu_ehad_TTBar_RW.root signal TreesMu_etau_TTBar_RW.root signal TreesMu_mue_TTBar_RW.root signal TreesMu_muhad_TTBar_RW.root signal TreesMu_mutau_TTBar_RW.root signal TreesMu_SbarChannel_RW.root signal TreesMu_SChannel_RW.root signal TreesMu_TbarChannel_RW.root signal TreesMu_TbarWChannel_RW.root signal TreesMu_TChannel_RW.root signal TreesMu_TWChannel_RW.root bkg TreesMu_bkg_RW.root wtemplate TreesMu_WTemplateDefFormat_RW.root data TreesMu_Data_plots.root > DD/mujet_10bin.txt

#./TestMDFit100 do3D yes channel mu is2Drecgen yes  signal TreesMu_die_TTBar_RW.root signal TreesMu_dimu_TTBar_RW.root signal TreesMu_disemitau_TTBar_RW.root signal TreesMu_ehad_TTBar_RW.root signal TreesMu_etau_TTBar_RW.root signal TreesMu_mue_TTBar_RW.root signal TreesMu_muhad_TTBar_RW.root signal TreesMu_mutau_TTBar_RW.root signal TreesMu_SbarChannel_RW.root signal TreesMu_SChannel_RW.root signal TreesMu_TbarChannel_RW.root signal TreesMu_TbarWChannel_RW.root signal TreesMu_TChannel_RW.root signal TreesMu_TWChannel_RW.root bkg TreesMu_bkg_RW.root wtemplate TreesMu_WTemplateDefFormat_RW.root data TreesMu_Data_plots.root > DD/mujet_100bin.txt

####--------- Dphi
./TestMDFit do3D yes channel mu is2Drecgen yes  signal TreesMu_die_TTBar_RW.root signal TreesMu_dimu_TTBar_RW.root signal TreesMu_disemitau_TTBar_RW.root signal TreesMu_ehad_TTBar_RW.root signal TreesMu_etau_TTBar_RW.root signal TreesMu_mue_TTBar_RW.root signal TreesMu_muhad_TTBar_RW.root signal TreesMu_mutau_TTBar_RW.root signal TreesMu_SbarChannel_RW.root signal TreesMu_SChannel_RW.root signal TreesMu_TbarChannel_RW.root signal TreesMu_TbarWChannel_RW.root signal TreesMu_TChannel_RW.root signal TreesMu_TWChannel_RW.root bkg TreesMu_bkgPhi_RW.root wtemplate TreesMu_WTemplateDefFormat_RW.root data TreesMu_Data_plots.root > DD/mujet_10bin_phi.txt

./TestMDFit100 do3D yes channel mu is2Drecgen yes  signal TreesMu_die_TTBar_RW.root signal TreesMu_dimu_TTBar_RW.root signal TreesMu_disemitau_TTBar_RW.root signal TreesMu_ehad_TTBar_RW.root signal TreesMu_etau_TTBar_RW.root signal TreesMu_mue_TTBar_RW.root signal TreesMu_muhad_TTBar_RW.root signal TreesMu_mutau_TTBar_RW.root signal TreesMu_SbarChannel_RW.root signal TreesMu_SChannel_RW.root signal TreesMu_TbarChannel_RW.root signal TreesMu_TbarWChannel_RW.root signal TreesMu_TChannel_RW.root signal TreesMu_TWChannel_RW.root bkg TreesMu_bkgPhi_RW.root wtemplate TreesMu_WTemplateDefFormat_RW.root data TreesMu_Data_plots.root > DD/mujet_100bin_phi.txt

####--------- Dr
./TestMDFit do3D yes channel mu is2Drecgen yes  signal TreesMu_die_TTBar_RW.root signal TreesMu_dimu_TTBar_RW.root signal TreesMu_disemitau_TTBar_RW.root signal TreesMu_ehad_TTBar_RW.root signal TreesMu_etau_TTBar_RW.root signal TreesMu_mue_TTBar_RW.root signal TreesMu_muhad_TTBar_RW.root signal TreesMu_mutau_TTBar_RW.root signal TreesMu_SbarChannel_RW.root signal TreesMu_SChannel_RW.root signal TreesMu_TbarChannel_RW.root signal TreesMu_TbarWChannel_RW.root signal TreesMu_TChannel_RW.root signal TreesMu_TWChannel_RW.root bkg TreesMu_bkgdr_RW.root wtemplate TreesMu_WTemplateDefFormat_RW.root data TreesMu_Data_plots.root > DD/mujet_10bin_dr.txt

./TestMDFit100 do3D yes channel mu is2Drecgen yes  signal TreesMu_die_TTBar_RW.root signal TreesMu_dimu_TTBar_RW.root signal TreesMu_disemitau_TTBar_RW.root signal TreesMu_ehad_TTBar_RW.root signal TreesMu_etau_TTBar_RW.root signal TreesMu_mue_TTBar_RW.root signal TreesMu_muhad_TTBar_RW.root signal TreesMu_mutau_TTBar_RW.root signal TreesMu_SbarChannel_RW.root signal TreesMu_SChannel_RW.root signal TreesMu_TbarChannel_RW.root signal TreesMu_TbarWChannel_RW.root signal TreesMu_TChannel_RW.root signal TreesMu_TWChannel_RW.root bkg TreesMu_bkgdr_RW.root wtemplate TreesMu_WTemplateDefFormat_RW.root data TreesMu_Data_plots.root > DD/mujet_100bin_dr.txt

